# Import Library

In [1]:
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
#model
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error
import xgboost
from xgboost import XGBRegressor

# Load Data

In [2]:
df = pd.read_excel('新竹_2020.xlsx')

In [3]:
df.head()

,測站,日期,測項,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
0,--------------------,--------------------,--------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,...,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------,-------------------------------
1,新竹,2020-01-01 00:00:00,AMB_TEMP,15.20,15.20,15.30,15.30,15.30,15.40,15.50,...,18.10,18.20,17.90,17.30,16.70,16.40,16.20,16.10,16,15.80
2,新竹,2020-01-01 00:00:00,CH4,1.74,1.74,1.77,1.78,1.77,1.77,1.77,...,1.78,1.78,1.77,1.80,1.81,1.82,1.85,1.83,1.92,1.94
3,新竹,2020-01-01 00:00:00,CO,0.28,0.25,0.24,0.22,0.20,0.19,0.20,...,0.28,0.29,0.28,0.34,0.39,0.41,0.46,0.49,0.58,0.52
4,新竹,2020-01-01 00:00:00,NMHC,0.06,0.07,0.05,0.05,0.05,0.05,0.07,...,0.09,0.09,0.07,0.08,0.12,0.12,0.16,0.14,0.17,0.20

In [4]:
#將第一行奇怪的東西刪除
df = df.drop([0])

In [5]:
df.head()

,測站,日期,測項,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
1,新竹,2020-01-01 00:00:00,AMB_TEMP,15.20,15.20,15.30,15.30,15.30,15.40,15.50,...,18.10,18.20,17.90,17.30,16.70,16.40,16.20,16.10,16,15.80
2,新竹,2020-01-01 00:00:00,CH4,1.74,1.74,1.77,1.78,1.77,1.77,1.77,...,1.78,1.78,1.77,1.80,1.81,1.82,1.85,1.83,1.92,1.94
3,新竹,2020-01-01 00:00:00,CO,0.28,0.25,0.24,0.22,0.20,0.19,0.20,...,0.28,0.29,0.28,0.34,0.39,0.41,0.46,0.49,0.58,0.52
4,新竹,2020-01-01 00:00:00,NMHC,0.06,0.07,0.05,0.05,0.05,0.05,0.07,...,0.09,0.09,0.07,0.08,0.12,0.12,0.16,0.14,0.17,0.20
5,新竹,2020-01-01 00:00:00,NO,0.30,0.60,0.60,0.60,0.30,0.30,0.50,...,1.60,1.60,1.20,0.70,0.90,1.10,1.10,1.70,1.80,1.40

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6588 entries, 1 to 6588
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   測站                    6588 non-null   object
 1   日期                    6588 non-null   object
 2   測項                    6588 non-null   object
 3   0                     6588 non-null   object
 4   1                     6588 non-null   object
 5   2                     6588 non-null   object
 6   3                     6588 non-null   object
 7   4                     6588 non-null   object
 8   5                     6588 non-null   object
 9   6                     6588 non-null   object
 10  7                     6588 non-null   object
 11  8                     6588 non-null   object
 12  9                     6588 non-null   object
 13  10                    6588 non-null   object
 14  11                    6588 non-null   object
 15  12                    6588 non-null   object
 16  13                    6588 non-null   object
 17  14                    6588 non-null   object
 18  15                    6588 non-null   object
 19  16                    6588 non-null   object
 20  17                    6588 non-null   object
 21  18                    6588 non-null   object
 22  19                    6588 non-null   object
 23  20                    6588 non-null   object
 24  21                    6588 non-null   object
 25  22                    6588 non-null   object
 26  23                    6588 non-null   object
dtypes: object(27)
memory usage: 1.4+ MB

# Data Preprocessing

In [7]:
df['日期                  ']

1       2020-01-01 00:00:00
2       2020-01-01 00:00:00
3       2020-01-01 00:00:00
4       2020-01-01 00:00:00
5       2020-01-01 00:00:00
               ...
6584    2020-12-31 00:00:00
6585    2020-12-31 00:00:00
6586    2020-12-31 00:00:00
6587    2020-12-31 00:00:00
6588    2020-12-31 00:00:00
Name: 日期                  , Length: 6588, dtype: object

In [8]:
#object轉成datetime形式
df['日期                  '] = pd.to_datetime(df['日期                  '],format='%m/%d/%Y %H:%M:%S')

In [9]:
df['日期                  ']

1      2020-01-01
2      2020-01-01
3      2020-01-01
4      2020-01-01
5      2020-01-01
          ...
6584   2020-12-31
6585   2020-12-31
6586   2020-12-31
6587   2020-12-31
6588   2020-12-31
Name: 日期                  , Length: 6588, dtype: datetime64[ns]

In [10]:
print(type(df['日期                  ']))
print(df['日期                  '].index)
print(type(df['日期                  '].index))

<class 'pandas.core.series.Series'>
Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            6579, 6580, 6581, 6582, 6583, 6584, 6585, 6586, 6587, 6588],
           dtype='int64', length=6588)
<class 'pandas.core.indexes.numeric.Int64Index'>

In [11]:
#取出10, 11, 12月資料
data = df[df['日期                  ']>= '2020-10-01']

In [12]:
data.head()

,測站,日期,測項,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
4933,新竹,2020-10-01,AMB_TEMP,23.70,23.80,23.80,23.90,23.90,23.80,24.10,...,29.90,29.60,28.70,27.50,26.40,25.70,25.50,25.30,24.90,24.50
4934,新竹,2020-10-01,CH4,1.97,1.95,1.96,1.96,1.95,1.96,1.97,...,1.97,1.98,1.97,2,2.03,2.04,2.05,2.02,2.10,2.14
4935,新竹,2020-10-01,CO,0.23,0.22,0.21,0.20,0.20,0.22,0.24,...,0.29,0.30,0.33,0.38,0.46,0.50,0.45,0.39,0.46,0.45
4936,新竹,2020-10-01,NMHC,0.06,0.05,0.03,0.03,0.03,0.04,0.04,...,0.06,0.07,0.09,0.11,0.13,0.15,0.10,0.07,0.12,0.18
4937,新竹,2020-10-01,NO,1.20,0.70,0.50,0.70,0.50,0.30,0.70,...,1.30,1,0.90,0.80,0.50,0.90,0.90,0.30,0.70,0.90

In [13]:
#reset index
data = data.reset_index(drop = True)
data

,測站,日期,測項,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
0,新竹,2020-10-01,AMB_TEMP,23.70,23.80,23.80,23.90,23.90,23.80,24.10,...,29.90,29.60,28.70,27.50,26.40,25.70,25.50,25.30,24.90,24.50
1,新竹,2020-10-01,CH4,1.97,1.95,1.96,1.96,1.95,1.96,1.97,...,1.97,1.98,1.97,2,2.03,2.04,2.05,2.02,2.10,2.14
2,新竹,2020-10-01,CO,0.23,0.22,0.21,0.20,0.20,0.22,0.24,...,0.29,0.30,0.33,0.38,0.46,0.50,0.45,0.39,0.46,0.45
3,新竹,2020-10-01,NMHC,0.06,0.05,0.03,0.03,0.03,0.04,0.04,...,0.06,0.07,0.09,0.11,0.13,0.15,0.10,0.07,0.12,0.18
4,新竹,2020-10-01,NO,1.20,0.70,0.50,0.70,0.50,0.30,0.70,...,1.30,1,0.90,0.80,0.50,0.90,0.90,0.30,0.70,0.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651,新竹,2020-12-31,THC,2.01,2.02,2,2,1.99,2,1.98,...,2.03,2.07,2.07,2.10,2.10,2.07,2.07,2.05,2.04,2.07
1652,新竹,2020-12-31,WD_HR,54,55,54,53,58,52,52,...,54,50,52,45,47,42,42,47,45,44
1653,新竹,2020-12-31,WIND_DIREC,53,52,57,58,49,54,36,...,48,43,44,33,50,40,46,46,51,38
1654,新竹,2020-12-31,WIND_SPEED,4.70,4.60,4.70,4.90,4.10,5.30,5.50,...,4.50,4.40,4.20,3.80,3.70,4.70,4.50,4.40,3.90,3.90
1655,新竹,2020-12-31,WS_HR,3.70,3.60,3.60,3.50,3.50,3.30,3.80,...,3.70,3.10,3.30,3.10,2.90,3.30,3.10,2.90,2.80,2.60

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1656 entries, 0 to 1655
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   測站                    1656 non-null   object
 1   日期                    1656 non-null   datetime64[ns]
 2   測項                    1656 non-null   object
 3   0                     1656 non-null   object
 4   1                     1656 non-null   object
 5   2                     1656 non-null   object
 6   3                     1656 non-null   object
 7   4                     1656 non-null   object
 8   5                     1656 non-null   object
 9   6                     1656 non-null   object
 10  7                     1656 non-null   object
 11  8                     1656 non-null   object
 12  9                     1656 non-null   object
 13  10                    1656 non-null   object
 14  11                    1656 non-null   object
 15  12                    1656 non-null   object
 16  13                    1656 non-null   object
 17  14                    1656 non-null   object
 18  15                    1656 non-null   object
 19  16                    1656 non-null   object
 20  17                    1656 non-null   object
 21  18                    1656 non-null   object
 22  19                    1656 non-null   object
 23  20                    1656 non-null   object
 24  21                    1656 non-null   object
 25  22                    1656 non-null   object
 26  23                    1656 non-null   object
dtypes: datetime64[ns](1), object(26)
memory usage: 349.4+ KB

In [15]:
#判斷是不是數值
def is_number(s):
    try: # 如果能运行float(s)语句，返回True(字符串s是浮点数)
        float(s)
        return True
    except ValueError: # ValueError为Python的一种标准异常，表示"传入无效的参数"
        pass
    try:
        import unicodedata # 处理ASCii码的包
        unicodedata.numeric(s) # 把一个表示数字的字符串转换为浮点数返回的函数
        return True
    except (TypeError, ValueError):
        pass
    return False

In [16]:
data_text = data.iloc[:, 0:3]
#print(data_text)
data_tmp = data.iloc[:,3:]
#print(data_tmp)
for i in range(1656):
    for j in range(24):
        if(is_number(data_tmp.iloc[i, j]) == False): #如果並非數值
            b = j
            a = i
            y = j
            x = i
            while(is_number(data_tmp.iloc[a,b]) == False):
                b = (b+23)%24
                if b == 23:
                    a = a-18
            while(is_number(data_tmp.iloc[x,y]) == False):
                y = (y+25)%24
                if y == 0:
                    x = x+18
                    if x>= 1655:
                        x = 1655
            data_tmp.iloc[i, j] = (data_tmp.iloc[a,b]+data_tmp.iloc[x,y])/2
data_tmp

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,23.70,23.80,23.80,23.90,23.90,23.80,24.10,24.70,26,27.20,...,29.90,29.60,28.70,27.50,26.40,25.70,25.50,25.30,24.90,24.50
1,1.97,1.95,1.96,1.96,1.95,1.96,1.97,1.97,1.96,1.98,...,1.97,1.98,1.97,2,2.03,2.04,2.05,2.02,2.10,2.14
2,0.23,0.22,0.21,0.20,0.20,0.22,0.24,0.29,0.27,0.33,...,0.29,0.30,0.33,0.38,0.46,0.50,0.45,0.39,0.46,0.45
3,0.06,0.05,0.03,0.03,0.03,0.04,0.04,0.05,0.06,0.07,...,0.06,0.07,0.09,0.11,0.13,0.15,0.10,0.07,0.12,0.18
4,1.20,0.70,0.50,0.70,0.50,0.30,0.70,0.90,1,1.80,...,1.30,1,0.90,0.80,0.50,0.90,0.90,0.30,0.70,0.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651,2.01,2.02,2,2,1.99,2,1.98,2,2.01,2.03,...,2.03,2.07,2.07,2.10,2.10,2.07,2.07,2.05,2.04,2.07
1652,54,55,54,53,58,52,52,35,52,56,...,54,50,52,45,47,42,42,47,45,44
1653,53,52,57,58,49,54,36,33,52,47,...,48,43,44,33,50,40,46,46,51,38
1654,4.70,4.60,4.70,4.90,4.10,5.30,5.50,5.60,3.80,3.50,...,4.50,4.40,4.20,3.80,3.70,4.70,4.50,4.40,3.90,3.90
1655,3.70,3.60,3.60,3.50,3.50,3.30,3.80,3.80,3.40,3,...,3.70,3.10,3.30,3.10,2.90,3.30,3.10,2.90,2.80,2.60

In [17]:
data_df = pd.DataFrame()
data_df = pd.concat([data_text, data_tmp], axis = 1)
data_df

,測站,日期,測項,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
0,新竹,2020-10-01,AMB_TEMP,23.70,23.80,23.80,23.90,23.90,23.80,24.10,...,29.90,29.60,28.70,27.50,26.40,25.70,25.50,25.30,24.90,24.50
1,新竹,2020-10-01,CH4,1.97,1.95,1.96,1.96,1.95,1.96,1.97,...,1.97,1.98,1.97,2,2.03,2.04,2.05,2.02,2.10,2.14
2,新竹,2020-10-01,CO,0.23,0.22,0.21,0.20,0.20,0.22,0.24,...,0.29,0.30,0.33,0.38,0.46,0.50,0.45,0.39,0.46,0.45
3,新竹,2020-10-01,NMHC,0.06,0.05,0.03,0.03,0.03,0.04,0.04,...,0.06,0.07,0.09,0.11,0.13,0.15,0.10,0.07,0.12,0.18
4,新竹,2020-10-01,NO,1.20,0.70,0.50,0.70,0.50,0.30,0.70,...,1.30,1,0.90,0.80,0.50,0.90,0.90,0.30,0.70,0.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651,新竹,2020-12-31,THC,2.01,2.02,2,2,1.99,2,1.98,...,2.03,2.07,2.07,2.10,2.10,2.07,2.07,2.05,2.04,2.07
1652,新竹,2020-12-31,WD_HR,54,55,54,53,58,52,52,...,54,50,52,45,47,42,42,47,45,44
1653,新竹,2020-12-31,WIND_DIREC,53,52,57,58,49,54,36,...,48,43,44,33,50,40,46,46,51,38
1654,新竹,2020-12-31,WIND_SPEED,4.70,4.60,4.70,4.90,4.10,5.30,5.50,...,4.50,4.40,4.20,3.80,3.70,4.70,4.50,4.40,3.90,3.90
1655,新竹,2020-12-31,WS_HR,3.70,3.60,3.60,3.50,3.50,3.30,3.80,...,3.70,3.10,3.30,3.10,2.90,3.30,3.10,2.90,2.80,2.60

In [18]:
#將資料切割成訓練集(10.11月)以及測試集(12月)
train = data_df[data_df['日期                  ']<'2020-12-01']
test = data_df[data_df['日期                  '] >= '2020-12-01']

In [19]:
print(train.shape)
print(test.shape)

(1098, 27)
(558, 27)

In [20]:
train = train.drop(['測站                  ','日期                  '], axis = 1)
train

,測項,0,1,2,3,4,5,6,7,8,...,14,15,16,17,18,19,20,21,22,23
0,AMB_TEMP,23.70,23.80,23.80,23.90,23.90,23.80,24.10,24.70,26,...,29.90,29.60,28.70,27.50,26.40,25.70,25.50,25.30,24.90,24.50
1,CH4,1.97,1.95,1.96,1.96,1.95,1.96,1.97,1.97,1.96,...,1.97,1.98,1.97,2,2.03,2.04,2.05,2.02,2.10,2.14
2,CO,0.23,0.22,0.21,0.20,0.20,0.22,0.24,0.29,0.27,...,0.29,0.30,0.33,0.38,0.46,0.50,0.45,0.39,0.46,0.45
3,NMHC,0.06,0.05,0.03,0.03,0.03,0.04,0.04,0.05,0.06,...,0.06,0.07,0.09,0.11,0.13,0.15,0.10,0.07,0.12,0.18
4,NO,1.20,0.70,0.50,0.70,0.50,0.30,0.70,0.90,1,...,1.30,1,0.90,0.80,0.50,0.90,0.90,0.30,0.70,0.90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1093,THC,1.95,1.94,1.95,1.96,1.95,1.95,1.95,1.96,1.99,...,1.98,2,1.99,2.03,2.01,2.04,2.02,2.02,2.02,2.01
1094,WD_HR,52,53,49,50,58,55,56,57,52,...,53,52,55,51,60,45,36,47,46,39
1095,WIND_DIREC,53,50,49,47,63,54,65,59,45,...,59,43,60,56,57,41,30,55,38,41
1096,WIND_SPEED,4.40,4.20,5.20,4.80,6.10,5.40,5.80,6.60,5.20,...,5.50,5.40,4.70,5.10,5.60,5.50,5.80,5.20,4.60,4.80
1097,WS_HR,3.50,3.60,3.60,3.80,3.90,4.10,4,4.50,4,...,4.60,4.20,3.80,3.80,4.50,4.10,5.30,3.80,3.40,3.90

In [21]:
df_train = pd.DataFrame()
df_train = train[0:18]
for i in range(18, train.shape[0], 18): #1098
    df_train = pd.merge(df_train, train[i:i+18], how = 'right',left_on='測項                  ', right_on = '測項                  ')

In [22]:
print(df_train.shape)
print(type(df_train))

(18, 1465)
<class 'pandas.core.frame.DataFrame'>

In [23]:
df_train = df_train.transpose()
df_train = df_train.reset_index(drop = True)
df_train = df_train.transpose()

In [24]:
df_train

,0,1,2,3,4,5,6,7,8,9,...,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464
0,AMB_TEMP,23.70,23.80,23.80,23.90,23.90,23.80,24.10,24.70,26,...,21.60,21.50,20.40,20,20.10,19.90,19.40,18.90,18.90,18.70
1,CH4,1.97,1.95,1.96,1.96,1.95,1.96,1.97,1.97,1.96,...,1.93,1.94,1.93,1.94,1.94,1.95,1.95,1.95,1.95,1.95
2,CO,0.23,0.22,0.21,0.20,0.20,0.22,0.24,0.29,0.27,...,0.26,0.27,0.27,0.29,0.29,0.31,0.25,0.22,0.20,0.18
3,NMHC,0.06,0.05,0.03,0.03,0.03,0.04,0.04,0.05,0.06,...,0.05,0.06,0.06,0.09,0.07,0.09,0.07,0.07,0.07,0.06
4,NO,1.20,0.70,0.50,0.70,0.50,0.30,0.70,0.90,1,...,2.50,2.40,2,1.80,1.60,1.60,1.80,1.70,1.60,1.60
5,NO2,8,6,5.50,5.20,5.30,5.80,8,7.60,6.60,...,4.50,5.40,6.60,9,7.50,8.60,6.90,6,4.80,4.10
6,NOx,9.20,6.70,6.10,5.80,5.80,6.30,8.60,8.50,7.60,...,6.90,7.70,8.50,10.80,9.10,10.30,8.70,7.80,6.30,5.70
7,O3,48,50.60,53.10,53,50.50,47.80,44.80,46.60,51.90,...,42.40,39.70,35.90,32.40,34.50,33.50,35.20,34.90,36.30,37.80
8,PM10,21,24,28,26,28,22,26,27,29,...,23,30,15,14,14,16,11,18,14,18
9,PM2.5,16,9,11,10,9,15,10,10,10,...,6,9,5,3,4,6,7,9,9,5
10,RAINFALL,0,0,0,0,0,0,0,0,0,...,0.20,0.20,0.40,0.40,0.40,0.60,0.40,0.60,0.80,0.60
11,RH,72,71,72,72,72,72,72,68,61,...,60,60,69,72,72,74,78,82,82,82
12,SO2,2,2.20,2.30,2.60,2.80,3,3.40,2.90,2.50,...,2.20,2.80,3.40,3.30,2.80,2.50,2,2.40,2.10,2.10
13,THC,2.03,2,1.99,1.99,1.98,2,2.01,2.02,2.02,...,1.98,2,1.99,2.03,2.01,2.04,2.02,2.02,2.02,2.01
14,WD_HR,49,49,52,55,54,54,55,46,48,...,53,52,55,51,60,45,36,47,46,39
15,WIND_DIREC,57,43,49,60,58,47,54,46,57,...,59,43,60,56,57,41,30,55,38,41
16,WIND_SPEED,3.70,2.90,3.30,3,3.20,2.50,2.90,3.10,4.20,...,5.50,5.40,4.70,5.10,5.60,5.50,5.80,5.20,4.60,4.80
17,WS_HR,2.50,2.20,2.50,2.50,2.40,2.30,2.10,2.40,3.10,...,4.60,4.20,3.80,3.80,4.50,4.10,5.30,3.80,3.40,3.90

In [25]:
test = test.drop(['測站                  ','日期                  '], axis = 1)
test

,測項,0,1,2,3,4,5,6,7,8,...,14,15,16,17,18,19,20,21,22,23
1098,AMB_TEMP,18.50,18.40,18.30,18.20,18.20,18.30,18.40,18.60,19.30,...,21.400,20.7000,20.10,19.80,19.70,19.90,20.50,20.60,20.50,20.30
1099,CH4,1.95,1.95,1.95,1.95,1.95,1.95,1.94,1.95,1.95,...,1.920,1.8900,1.94,1.95,1.96,1.94,1.91,1.91,1.91,1.92
1100,CO,0.17,0.16,0.16,0.16,0.16,0.17,0.17,0.25,0.28,...,0.220,0.2000,0.25,0.33,0.37,0.32,0.25,0.22,0.21,0.20
1101,NMHC,0.06,0.05,0.06,0.06,0.04,0.06,0.03,0.08,0.09,...,0.070,0.0800,0.11,0.15,0.16,0.12,0.06,0.04,0.04,0.05
1102,NO,1.30,1.50,1.20,1.30,1.20,1.30,1.30,1.90,3.40,...,2.775,2.5375,2.30,1.90,1.70,1.60,1.40,1.20,1,1.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1651,THC,2.01,2.02,2,2,1.99,2,1.98,2,2.01,...,2.030,2.0700,2.07,2.10,2.10,2.07,2.07,2.05,2.04,2.07
1652,WD_HR,54,55,54,53,58,52,52,35,52,...,54,50,52,45,47,42,42,47,45,44
1653,WIND_DIREC,53,52,57,58,49,54,36,33,52,...,48,43,44,33,50,40,46,46,51,38
1654,WIND_SPEED,4.70,4.60,4.70,4.90,4.10,5.30,5.50,5.60,3.80,...,4.500,4.4000,4.20,3.80,3.70,4.70,4.50,4.40,3.90,3.90
1655,WS_HR,3.70,3.60,3.60,3.50,3.50,3.30,3.80,3.80,3.40,...,3.700,3.1000,3.30,3.10,2.90,3.30,3.10,2.90,2.80,2.60

In [26]:
df_test = pd.DataFrame()
df_test = test[0:18]
for i in range(18, test.shape[0], 18): #1098
    df_test = pd.merge(df_test, test[i:i+18], how = 'right',left_on='測項                  ', right_on = '測項                  ')

In [27]:
df_test = df_test.transpose()
df_test = df_test.reset_index(drop = True)
df_test = df_test.transpose()

In [28]:
df_test

,0,1,2,3,4,5,6,7,8,9,...,735,736,737,738,739,740,741,742,743,744
0,AMB_TEMP,18.50,18.40,18.30,18.20,18.20,18.30,18.40,18.60,19.30,...,11.20,11,10.8000,10.50000,10.500000,10.600000,10.800000,10.900000,11,11
1,CH4,1.95,1.95,1.95,1.95,1.95,1.95,1.94,1.95,1.95,...,1.97,1.980,1.9800,1.99000,1.990000,1.990000,1.980000,1.980000,1.970000,1.990000
2,CO,0.17,0.16,0.16,0.16,0.16,0.17,0.17,0.25,0.28,...,0.28,0.300,0.3100,0.34000,0.340000,0.310000,0.290000,0.280000,0.260000,0.300000
3,NMHC,0.06,0.05,0.06,0.06,0.04,0.06,0.03,0.08,0.09,...,0.06,0.090,0.0900,0.11000,0.110000,0.080000,0.090000,0.070000,0.070000,0.080000
4,NO,1.30,1.50,1.20,1.30,1.20,1.30,1.30,1.90,3.40,...,3.40,3,2.8000,2.30000,2.100000,1.600000,1.500000,1.500000,1.400000,1.400000
5,NO2,3,2.90,3.80,3.60,3.60,4.20,4.70,7.40,9,...,7.40,10.300,11.9000,13.70000,13.100000,10.800000,9.300000,8.600000,7.700000,9.700000
6,NOx,4.40,4.50,5,4.90,4.80,5.50,6,9.30,12.40,...,10.80,13.300,14.8000,16,15.200000,12.400000,10.800000,10.200000,9.100000,11.100000
7,O3,38.70,37.80,35.90,35.60,35.40,33.70,33.50,30.90,30.80,...,30.70,28.300,27.1000,25.10000,26.200000,28.400000,28.900000,29.500000,29.700000,25.800000
8,PM10,17,13,12,10,5,13,15,12,12,...,32,36,25,34,30,31,27,26,23,27
9,PM2.5,5,9,7,4,5,11,7,5,5,...,15,16,20,12,17,13,12,15,18,15
10,RAINFALL,0.80,0.60,1,1,0.80,0.80,0.80,1,0.80,...,0,0,0,0,0,0,0,0,0,0
11,RH,85,86,87,87,86,86,87,86,85,...,58,60,61,62,62,61,61,60,60,62
12,SO2,0.50,1.90,1.80,1.80,1.80,2,1.80,2.50,3.10,...,3.75,3.725,3.7125,3.70625,3.703125,3.701563,3.700781,3.700391,3.700195,3.700098
13,THC,2.01,2,2.01,2.01,1.99,2.01,1.97,2.03,2.04,...,2.03,2.070,2.0700,2.10000,2.100000,2.070000,2.070000,2.050000,2.040000,2.070000
14,WD_HR,43,45,49,43,50,35,36,34,34,...,54,50,52,45,47,42,42,47,45,44
15,WIND_DIREC,31,38,40,47,55,37,30,41,35,...,48,43,44,33,50,40,46,46,51,38
16,WIND_SPEED,4.30,4.20,3.80,3.90,4.70,5.30,4.30,4,4.60,...,4.50,4.400,4.2000,3.80000,3.700000,4.700000,4.500000,4.400000,3.900000,3.900000
17,WS_HR,3.50,3,3,3.10,3,4,3.60,3.30,3.70,...,3.70,3.100,3.3000,3.10000,2.900000,3.300000,3.100000,2.900000,2.800000,2.600000

# Time Series

### 將未來第一個小時當預測目標

#### 1. X 只取 PM2.5

In [29]:
df_train_drop = df_train.drop([0], axis = 1)
df_train_drop

,1,2,3,4,5,6,7,8,9,10,...,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464
0,23.70,23.80,23.80,23.90,23.90,23.80,24.10,24.70,26,27.20,...,21.60,21.50,20.40,20,20.10,19.90,19.40,18.90,18.90,18.70
1,1.97,1.95,1.96,1.96,1.95,1.96,1.97,1.97,1.96,1.98,...,1.93,1.94,1.93,1.94,1.94,1.95,1.95,1.95,1.95,1.95
2,0.23,0.22,0.21,0.20,0.20,0.22,0.24,0.29,0.27,0.33,...,0.26,0.27,0.27,0.29,0.29,0.31,0.25,0.22,0.20,0.18
3,0.06,0.05,0.03,0.03,0.03,0.04,0.04,0.05,0.06,0.07,...,0.05,0.06,0.06,0.09,0.07,0.09,0.07,0.07,0.07,0.06
4,1.20,0.70,0.50,0.70,0.50,0.30,0.70,0.90,1,1.80,...,2.50,2.40,2,1.80,1.60,1.60,1.80,1.70,1.60,1.60
5,8,6,5.50,5.20,5.30,5.80,8,7.60,6.60,8,...,4.50,5.40,6.60,9,7.50,8.60,6.90,6,4.80,4.10
6,9.20,6.70,6.10,5.80,5.80,6.30,8.60,8.50,7.60,9.80,...,6.90,7.70,8.50,10.80,9.10,10.30,8.70,7.80,6.30,5.70
7,48,50.60,53.10,53,50.50,47.80,44.80,46.60,51.90,55.80,...,42.40,39.70,35.90,32.40,34.50,33.50,35.20,34.90,36.30,37.80
8,21,24,28,26,28,22,26,27,29,23,...,23,30,15,14,14,16,11,18,14,18
9,16,9,11,10,9,15,10,10,10,9,...,6,9,5,3,4,6,7,9,9,5
10,0,0,0,0,0,0,0,0,0,0,...,0.20,0.20,0.40,0.40,0.40,0.60,0.40,0.60,0.80,0.60
11,72,71,72,72,72,72,72,68,61,55,...,60,60,69,72,72,74,78,82,82,82
12,2,2.20,2.30,2.60,2.80,3,3.40,2.90,2.50,2.40,...,2.20,2.80,3.40,3.30,2.80,2.50,2,2.40,2.10,2.10
13,2.03,2,1.99,1.99,1.98,2,2.01,2.02,2.02,2.05,...,1.98,2,1.99,2.03,2.01,2.04,2.02,2.02,2.02,2.01
14,49,49,52,55,54,54,55,46,48,47,...,53,52,55,51,60,45,36,47,46,39
15,57,43,49,60,58,47,54,46,57,38,...,59,43,60,56,57,41,30,55,38,41
16,3.70,2.90,3.30,3,3.20,2.50,2.90,3.10,4.20,4.30,...,5.50,5.40,4.70,5.10,5.60,5.50,5.80,5.20,4.60,4.80
17,2.50,2.20,2.50,2.50,2.40,2.30,2.10,2.40,3.10,3.40,...,4.60,4.20,3.80,3.80,4.50,4.10,5.30,3.80,3.40,3.90

In [30]:
df_test_drop = df_test.drop([0], axis = 1)
df_test_drop

,1,2,3,4,5,6,7,8,9,10,...,735,736,737,738,739,740,741,742,743,744
0,18.50,18.40,18.30,18.20,18.20,18.30,18.40,18.60,19.30,20.30,...,11.20,11,10.8000,10.50000,10.500000,10.600000,10.800000,10.900000,11,11
1,1.95,1.95,1.95,1.95,1.95,1.95,1.94,1.95,1.95,1.95,...,1.97,1.980,1.9800,1.99000,1.990000,1.990000,1.980000,1.980000,1.970000,1.990000
2,0.17,0.16,0.16,0.16,0.16,0.17,0.17,0.25,0.28,0.27,...,0.28,0.300,0.3100,0.34000,0.340000,0.310000,0.290000,0.280000,0.260000,0.300000
3,0.06,0.05,0.06,0.06,0.04,0.06,0.03,0.08,0.09,0.11,...,0.06,0.090,0.0900,0.11000,0.110000,0.080000,0.090000,0.070000,0.070000,0.080000
4,1.30,1.50,1.20,1.30,1.20,1.30,1.30,1.90,3.40,4,...,3.40,3,2.8000,2.30000,2.100000,1.600000,1.500000,1.500000,1.400000,1.400000
5,3,2.90,3.80,3.60,3.60,4.20,4.70,7.40,9,7.90,...,7.40,10.300,11.9000,13.70000,13.100000,10.800000,9.300000,8.600000,7.700000,9.700000
6,4.40,4.50,5,4.90,4.80,5.50,6,9.30,12.40,11.80,...,10.80,13.300,14.8000,16,15.200000,12.400000,10.800000,10.200000,9.100000,11.100000
7,38.70,37.80,35.90,35.60,35.40,33.70,33.50,30.90,30.80,32.30,...,30.70,28.300,27.1000,25.10000,26.200000,28.400000,28.900000,29.500000,29.700000,25.800000
8,17,13,12,10,5,13,15,12,12,17,...,32,36,25,34,30,31,27,26,23,27
9,5,9,7,4,5,11,7,5,5,5,...,15,16,20,12,17,13,12,15,18,15
10,0.80,0.60,1,1,0.80,0.80,0.80,1,0.80,0.40,...,0,0,0,0,0,0,0,0,0,0
11,85,86,87,87,86,86,87,86,85,80,...,58,60,61,62,62,61,61,60,60,62
12,0.50,1.90,1.80,1.80,1.80,2,1.80,2.50,3.10,3.30,...,3.75,3.725,3.7125,3.70625,3.703125,3.701563,3.700781,3.700391,3.700195,3.700098
13,2.01,2,2.01,2.01,1.99,2.01,1.97,2.03,2.04,2.06,...,2.03,2.070,2.0700,2.10000,2.100000,2.070000,2.070000,2.050000,2.040000,2.070000
14,43,45,49,43,50,35,36,34,34,37,...,54,50,52,45,47,42,42,47,45,44
15,31,38,40,47,55,37,30,41,35,35,...,48,43,44,33,50,40,46,46,51,38
16,4.30,4.20,3.80,3.90,4.70,5.30,4.30,4,4.60,5.30,...,4.50,4.400,4.2000,3.80000,3.700000,4.700000,4.500000,4.400000,3.900000,3.900000
17,3.50,3,3,3.10,3,4,3.60,3.30,3.70,4,...,3.70,3.100,3.3000,3.10000,2.900000,3.300000,3.100000,2.900000,2.800000,2.600000

In [43]:
x_train = np.zeros((df_train_drop.shape[1]-6,6))
x_test= np.zeros((df_test_drop.shape[1]-6,6))

y_train = np.zeros((df_train_drop.shape[1]-6,1))
y_test = np.zeros((df_test_drop.shape[1]-6,1))

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

for i in range(0,x_train.shape[0]):
    x_train[i] = df_train_drop.iloc[9,i:i+6]
    y_train[i] = df_train_drop.iloc[9,i+6]
    
for i in range(0,x_test.shape[0]):
    x_test[i] = df_test_drop.iloc[9,i:i+6]
    y_test[i] = df_test_drop.iloc[9,i+6]

(1458, 6)
(738, 6)
(1458, 1)
(738, 1)

## Create Model

- Linear Regression with X: PM (將未來第一個小時當預測目標)

In [32]:
# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(x_train, y_train)

# Make predictions using the testing set
y_pred = regr.predict(x_test)


print("Linear Regression predict one hour (X: PM 2.5)", end = "\n")
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("Mean absolute error: %.2f" % mean_absolute_error(y_test, y_pred))

Linear Regression predict one hour (X: PM 2.5)
Mean squared error: 11.84
Mean absolute error: 2.52

- XGBoost with X: PM (將未來第一個小時當預測目標)

In [46]:
XGB = XGBRegressor(n_estimators=10, gamma = 35) #調整XGBoost參數 
XGB.fit(x_train, y_train)
y_pred = XGB.predict(x_test)


print("XGBoost predict one hour (X: PM 2.5)", end = "\n")
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("Mean absolute error: %.2f" % mean_absolute_error(y_test, y_pred))

XGBoost predict one hour (X: PM 2.5)
Mean squared error: 16.62
Mean absolute error: 2.70

#### 2. X 取所有18種屬性

In [34]:
x_train_all = np.array(df_train_drop.iloc[:, 0:6]).flatten()
for i in range(1,df_train_drop.shape[1]-6):
    x_train_all = np.vstack((x_train_all, np.array(df_train_drop.iloc[:,i:i+6]).flatten()))
y_train_all = np.array(df_train_drop.iloc[9, 6:df_train_drop.shape[1]])
    
x_test_all= np.array(df_test_drop.iloc[:,0:6]).flatten()
for i in range(1,df_test_drop.shape[1]-6):
    x_test_all = np.vstack((x_test_all, np.array(df_test_drop.iloc[:,i:i+6]).flatten()))
y_test_all = np.array(df_test_drop.iloc[9, 6:df_test_drop.shape[1]])


print(x_train_all.shape)
print(x_test_all.shape)
print(y_train_all.shape)
print(y_test_all.shape)

(1458, 108)
(738, 108)
(1458,)
(738,)

- Linear Regression with X: 18種屬性 (將未來第一個小時當預測目標)

In [35]:
# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(x_train_all, y_train_all)

# Make predictions using the testing set
y_pred_all = regr.predict(x_test_all)

print("Linear Regression predict one hour (X: 18種屬性)", end = "\n")
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test_all, y_pred_all))
print("Mean absolute error: %.2f" % mean_absolute_error(y_test_all, y_pred_all))

Linear Regression predict one hour (X: 18種屬性)
Mean squared error: 13.88
Mean absolute error: 2.69

- XGBoost with X: 18種屬性 (將未來第一個小時當預測目標)

In [36]:
XGB = XGBRegressor(n_estimators=20, gamma = 40) #調整XGBoost參數 
XGB.fit(x_train_all, y_train_all)
y_pred_all = XGB.predict(x_test_all)


print("XGBoost predict one hour (X: 18種屬性)", end = "\n")
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test_all, y_pred_all))
print("Mean absolute error: %.2f" % mean_absolute_error(y_test_all, y_pred_all))

XGBoost predict one hour (X: 18種屬性)
Mean squared error: 15.02
Mean absolute error: 2.69

### 將未來第六個小時當預測目標

#### 1. X 只取 PM2.5

In [37]:
x_train = np.zeros((df_train_drop.shape[1]-11,6))
x_test= np.zeros((df_test_drop.shape[1]-11,6))

y_train = np.zeros((df_train_drop.shape[1]-11,1))
y_test = np.zeros((df_test_drop.shape[1]-11,1))

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

for i in range(0,x_train.shape[0]):
    x_train[i] = df_train_drop.iloc[9,i:i+6]
    y_train[i] = df_train_drop.iloc[9,i+11]
    
for i in range(0,x_test.shape[0]):
    x_test[i] = df_test_drop.iloc[9,i:i+6]
    y_test[i] = df_test_drop.iloc[9,i+11]

(1453, 6)
(733, 6)
(1453, 1)
(733, 1)

## Create Model

- Linear Regression with X: PM 2.5 (將未來第六個小時當預測目標)

In [38]:
# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(x_train, y_train)

# Make predictions using the testing set
y_pred = regr.predict(x_test)

print("Linear Regression predict six hour (X: PM 2.5)", end = "\n")
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("Mean absolute error: %.2f" % mean_absolute_error(y_test, y_pred))

Linear Regression predict six hour (X: PM 2.5)
Mean squared error: 41.64
Mean absolute error: 4.58

- XGBoost with X: PM 2.5 (將未來第六個小時當預測目標)

In [39]:
XGB = XGBRegressor(n_estimators=10, gamma = 60) #調整XGBoost參數 
XGB.fit(x_train, y_train)
y_pred = XGB.predict(x_test)

print("XGBoost predict six hour (X: PM 2.5)", end = "\n")
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("Mean absolute error: %.2f" % mean_absolute_error(y_test, y_pred))

XGBoost predict six hour (X: PM 2.5)
Mean squared error: 45.68
Mean absolute error: 4.77

#### 2. X 取18種屬性

In [40]:
x_train_all = np.array(df_train_drop.iloc[:, 0:6]).flatten()
for i in range(1,df_train_drop.shape[1]-11):
    x_train_all = np.vstack((x_train_all, np.array(df_train_drop.iloc[:,i:i+6]).flatten()))
y_train_all = np.array(df_train_drop.iloc[9, 11:df_train_drop.shape[1]])
    
x_test_all= np.array(df_test_drop.iloc[:,0:6]).flatten()
for i in range(1,df_test_drop.shape[1]-11):
    x_test_all = np.vstack((x_test_all, np.array(df_test_drop.iloc[:,i:i+6]).flatten()))
y_test_all = np.array(df_test_drop.iloc[9, 11:df_test_drop.shape[1]])


print(x_train_all.shape)
print(x_test_all.shape)
print(y_train_all.shape)
print(y_test_all.shape)

(1453, 108)
(733, 108)
(1453,)
(733,)

- Linear Regression with X: 所有18種屬性 (將未來第六個小時當預測目標)

In [41]:
# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(x_train_all, y_train_all)

# Make predictions using the testing set
y_pred_all = regr.predict(x_test_all)

print("Linear Regression predict six hour (X: 18種屬性)", end = "\n")
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test_all, y_pred_all))
print("Mean absolute error: %.2f" % mean_absolute_error(y_test_all, y_pred_all))

Linear Regression predict six hour (X: 18種屬性)
Mean squared error: 58.03
Mean absolute error: 6.09

- XGBoost with X: 所有18種屬性 (將未來第六個小時當預測目標)

In [42]:
XGB = XGBRegressor(n_estimators=20, gamma = 60) #調整XGBoost參數 
XGB.fit(x_train_all, y_train_all)
y_pred_all = XGB.predict(x_test_all)


print("XGBoost predict one hour (X: 18種屬性)", end = "\n")
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(y_test_all, y_pred_all))
print("Mean absolute error: %.2f" % mean_absolute_error(y_test_all, y_pred_all))

XGBoost predict one hour (X: 18種屬性)
Mean squared error: 44.53
Mean absolute error: 4.58